### ISSUE TITLE
AssertionError after saving a file with a compile error in it

### ISSUE THREAD

**Issue by rolandzwaga** [RandoriAS/randori-plugin-intellij#20]
How to reproduce:
1. Create new project
2. Add a new Randori class
3. Type random characters in the class implementation (to force a compile error)
4. Press Ctrl+S to save file

(We have now determined that this error only happens in the buildserver generated plugin)

This error is then generated:

null: null
java.lang.AssertionError: null
    at com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:55)
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:69)
    at com.intellij.util.ui.UIUtil.invokeAndWaitIfNeeded(UIUtil.java:1994)
    at randori.plugin.components.FileChangeListener.executeMakeInUIThread(FileChangeListener.java:112)
    at randori.plugin.components.FileChangeListener.access$000(FileChangeListener.java:45)
    at randori.plugin.components.FileChangeListener$1.run(FileChangeListener.java:89)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:495)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:185)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:226)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:175)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$8.run(ProgressManagerImpl.java:400)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:454)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:152)

**Comment by doublefx** [comment]
I can not reproduce with the compiled source code, maybe a build script problem, sent you my plugin script version, hope you'll find a diff, if not it could be a question to ask to jetbrains.

In between, can users trust the nightly builds ?
How do we want to communicate on it ?

**Comment by doublefx** [comment]
I opened a ticket at JetBrains http://devnet.jetbrains.com/message/5496270#5496270
