### ISSUE TITLE
IntelliJ Fatal Error

### ISSUE THREAD

**Issue by jcfranco** [RandoriAS/randori-plugin-intellij#27]
Occured with IntelliJ 12.1.4 (129.713 ) while following step 3 of https://github.com/RandoriAS/randori-plugin-intellij/wiki/Lesson-03-Bootstrap-and-Adding-a-Behavior

```
null: null
java.lang.AssertionError: null
    at com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:55)
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:69)
    at com.intellij.util.ui.UIUtil.invokeAndWaitIfNeeded(UIUtil.java:1994)
    at randori.plugin.components.FileChangeListener.executeMakeInUIThread(FileChangeListener.java:101)
    at randori.plugin.components.FileChangeListener.access$000(FileChangeListener.java:43)
    at randori.plugin.components.FileChangeListener$1.run(FileChangeListener.java:88)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:495)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:185)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:226)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:175)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$8.run(ProgressManagerImpl.java:400)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:454)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:680)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:152)

```

**Comment by labriola** [comment]
Hmmm. Okay, we will take a look. Already pinged the folks working on the plugin to ensure they saw the issue

**Comment by doublefx** [comment]
Duplicated with issue #20 

In short:

From the version 0.3.0.6, the user is invited to use CTRL+F9 to "Make Project" or map CTRL+S to it as describe here https://plus.google.com/102781722280464657997/posts/WUionZFzn7H

In detail:

1- The "Make on save" feature as implemented in Randori was working on the same model than the one used in the "Eclipse Mode" plugin, there are no other ways to implement it AFAIK.

2- This model is broken since IDEA 12, I haven't see it before because it is still working when the plugin is not externally build by Ant or the "Prepare Plugin" Action but launched directly by the IDE, which is what I do to test the plugin usually but not what is done to publish it.

3- Even though this feature was working but the user has the "Eclipse Mode" plugin installed, it would have created issues.

4- It is not the IntelliJ way to "Make on Save",

Links:

Eclipse Mode plug-in is obsolete and is not compatible with the recent IDEA 12+ builds.
Why the "Make on Save" is not the IntelliJ way and how they do better.
http://stackoverflow.com/questions/12744303/intellij-idea-java-classes-not-auto-compiling-on-save

I anyway opened a ticket at Jetbrains, it is not answered yet:
http://devnet.jetbrains.com/message/5496270#5496270

The nightly builds:
http://randoriframework.com/nightly-builds/
